name: Supabase CRONs PROD

on:
  schedule:
    - cron: "0 0 * * *"   # tous les jours à minuit UTC
jobs:
  run-crons:
    runs-on: ubuntu-latest
    steps:
      - name: Call calculate-daily-earnings
        run: |
          curl -s -o response.json -w "%{http_code}" -X POST "https://rmnarrqtrmghuqehdtnv.supabase.co/functions/v1/calculate-daily-earnings" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json"
          echo "Response:"
          cat response.json

      - name: Call process-referral-bonuses
        run: |
          curl -s -o response.json -w "%{http_code}" -X POST "https://rmnarrqtrmghuqehdtnv.supabase.co/functions/v1/check-staking-maturity" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json"
          echo "Response:"
          cat response.json

      - name: Call handle-payment-webhook
        run: |
          curl -s -o response.json -w "%{http_code}" -X POST "https://rmnarrqtrmghuqehdtnv.supabase.co/functions/v1/catch-up-earnings" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json"
          echo "Response:"
          cat response.json
